### ISSUE TITLE
PromptSupport might loose style

### ISSUE THREAD

**Issue by wimjongman** [EclipseNebula/nebula#15]
When the user adds a prompt support to a text widget, the prompt support retrieves the style (colors and font) from the widget but does not keep track of intermediate changes to the text widget regarding this style (color and font).

This might result in problems when the user changes the style after prompt support was added to the widget. e.g. the original styles might be disposed.

**Comment by lcaron** [comment]
Wim,
I worked on this subject and I'm facing a big problem: I can not handle color/font changes on the parent control (there's no listener).

The only way I found is using AOP... Or provide a method that refresh the Prompt after a color or font change (in this case this is not automatic and code should be added after each change)

What do you think ?

Laurent

**Comment by wimjongman** [comment]
A wild guess but could you add yourself to the dispose listener to the current font and color and do something if this get's called.

________________________________

**Comment by lcaron** [comment]
Good idea but IMHO it solves only some cases. For example in our application we use a "ResourceManager", a big cache that stores disposable elements (fonts, colors...).
So if in the style changes after the PromptSupport has been initialised, I won't be informed of that because the style may have not been disposed.

In order to solve this issue, I see only 3 solutions: 
a) Use AOP to intercept changes on font and colors
b) Create a public method that stores the changes. But in this case, the developper have to call this method after each change
c) In PromptSupport I create method to change the style of the "prompt-decorated" widget, but we will face the same problem: the developer has to use these methods instead of using setBackground(), setFont() and so on on the source widget.

Tricky problem, I'm still investigating...

**Comment by lcaron** [comment]
2 years after, I have no simple answer, so I've decided to close this issue
