### ISSUE TITLE
CDateTime NullPointerException when setting foreground color

### ISSUE THREAD

**Issue by ceugster** [EclipseNebula/nebula#280]
When I try to set the foreground color of a CDateTime widget, I get a NullPointerException. The Exception is thrown at following point in the CDateTime class:

`	public void setForeground(Color color) {
		super.setForeground(color);
		picker.updateColorsAndFont();
	}
`
The CDateTime widget is instantiated as follows:

`			CDateTime dateTime = new CDateTime(composite, fieldIdentifier.styles());
			dateTime.setLayoutData(fieldIdentifier.gridData());
			dateTime.setNullText(""); //$NON-NLS-1$
`
and fieldIdentifier.styles() is `CDT.BORDER | CDT.DROP_DOWN | CDT.DATE_MEDIUM | CDT.TIME_SHORT`

The code tries to update the color of the picker widget. This widget is null. Maybe I am doing something wrong? What if so?

**Comment by lcaron** [comment]
Hi Christian

This bug was know and fixed in Nebula 2.4.2 - please check https://github.com/eclipse/nebula/blob/257222bde16642b7668c465209a55fbf2629dc1a/widgets/cdatetime/org.eclipse.nebula.widgets.cdatetime/src/org/eclipse/nebula/widgets/cdatetime/CDateTime.java#L2258
https://github.com/eclipse/nebula/blob/257222bde16642b7668c465209a55fbf2629dc1a/widgets/cdatetime/org.eclipse.nebula.widgets.cdatetime/src/org/eclipse/nebula/widgets/cdatetime/CDateTime.java#L2259
https://github.com/eclipse/nebula/blob/257222bde16642b7668c465209a55fbf2629dc1a/widgets/cdatetime/org.eclipse.nebula.widgets.cdatetime/src/org/eclipse/nebula/widgets/cdatetime/CDateTime.java#L2260
https://github.com/eclipse/nebula/blob/257222bde16642b7668c465209a55fbf2629dc1a/widgets/cdatetime/org.eclipse.nebula.widgets.cdatetime/src/org/eclipse/nebula/widgets/cdatetime/CDateTime.java#L2261
https://github.com/eclipse/nebula/blob/257222bde16642b7668c465209a55fbf2629dc1a/widgets/cdatetime/org.eclipse.nebula.widgets.cdatetime/src/org/eclipse/nebula/widgets/cdatetime/CDateTime.java#L2262

Please update Nebula (the url is https://www.eclipse.org/nebula/downloads.php)

Keep us informed please.

**Comment by ceugster** [comment]
Hi Caron
Thank your for the fast answer. I did not find any information in the eclipse forum.
Best wishes Christian

**Comment by lcaron** [comment]
Hi Christian,

Did you tried with the latest release of Nebula ?
