### ISSUE TITLE
mvn clean verify fails on the root project with DuplicateProjectException

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#378]
If I run mvn clean verify in the root of the project I get:

org.eclipse.nebula.examples is duplicated in the reactor.

**Comment by vogella** [comment]
Looks like both include the examples in their pom, I will send a PR

**Comment by vogella** [comment]
Can this be reopened? I will try to solve it differently.

**Comment by wimjongman** [comment]
Lars, I'm not sure if this is actually broken. The build is split in two because we regard this as two separate "projects" each with their distinct releng. The examples view is shared between them. 

* Release
Contains the stable and maintained widgets which are released periodically

* Incubation
Contains new and unmaintained widgets.

**Comment by vogella** [comment]
Still would be nice to build them together.... Expect a PR soon...
